name: SkyCube
main: vin.ash.skycube.Main
author: Asra
version: 1.4.8
description: A Plugin for a small Sky Cube minigame, its like Sky Block but smaller
api-version: 1.16
api: [4.0.0]

commands:
  helpme:
    aliases: [helpm, h]
    description: This is command to help the player by giving them the help book
  tpr:
    aliases: [teleportr]
    description: Allows for teleporting